# Generated by Django 5.0.7 on 2024-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
