# Generated by Django 5.0.7 on 2024-07-25 17:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_datecreation_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 11, 7, 55, 324478)),
        ),
    ]
